### ISSUE TITLE
abandance map

### ISSUE THREAD

**Issue by shayerfg** [laugh12321/DACN#20]
While running the 'DACN' code, I encountered a minor issue regarding the output results. Specifically, I did not obtain the expected extraction abundance and loss graph that was mentioned in the code documentation.

**Comment by panskai** [comment]
我也是这个问题，你解决了吗？

**Comment by laugh12321** [comment]
I did not provide any code related to the drawing in this repository, but the data that the drawing relies on is in the 'results' folder. For detailed descriptions of the data in the folder, please refer to this link https://github.com/laugh12321/DACN/discussions/5#discussioncomment -5891943
